### ISSUE TITLE
`input size too long` when user can list all namespaces

### ISSUE THREAD

**Issue by theSuess** [observatorium/opa-openshift#11]
I've recently set up openshift-logging 5.5 on our cluster, which utilizes this project to enforce authz for loki. Regular users can access the logs but users with access to all namespaces run into an issue with the maximum query size in loki.

I've noticed that #10 includes changes to this part, and just wanted to report that large namespace lists can break querying all together.

Regarding resolution, I think a SAR for `list namespaces` might be useful. Then we could replace the matcher with `.*` instead.

**Comment by periklis** [comment]
#10 will address adding the `.*` regex matcher for this use case. Stay tuned.
